/*
 * Copyright (C) 2015  Pablo Sepúlveda P. (psep_AT_ti-nova_dot_cl)
 * 
 * This file is part of the beneficiosweb.
 * beneficiosweb is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * beneficiosweb is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with beneficiosweb.  If not, see <http://www.gnu.org/licenses/>.
 */
package cl.jbug.jbpm.beneficios;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("RUN del Solicitante")
	private java.lang.Integer run;
	@org.kie.api.definition.type.Label("Nombre Completo")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("Edad del Solicitante")
	private java.lang.Integer edad;
	@org.kie.api.definition.type.Label("N\u00B0 de Hijos")
	private java.lang.Integer numHijos;
	@org.kie.api.definition.type.Label("Estado Civil")
	private java.lang.Integer estadoCivil;
	@org.kie.api.definition.type.Label("Sueldo del Solicitante")
	private java.lang.Integer sueldo;
	@org.kie.api.definition.type.Label("Sexo del Solicitante")
	private java.lang.Integer sexo;

	@org.kie.api.definition.type.Label("Monto Total del Bono")
	private int montoBono;

	@org.kie.api.definition.type.Label("Mensaje de Respuesta")
	private java.lang.String mensaje;

	public Solicitante() {
		this.montoBono = 0;
		this.mensaje = "";
	}

	public java.lang.Integer getRun() {
		return this.run;
	}

	public void setRun(java.lang.Integer run) {
		this.run = run;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Integer getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.Integer edad) {
		this.edad = edad;
	}

	public java.lang.Integer getNumHijos() {
		return this.numHijos;
	}

	public void setNumHijos(java.lang.Integer numHijos) {
		this.numHijos = numHijos;
	}

	public java.lang.Integer getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(java.lang.Integer estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public java.lang.Integer getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(java.lang.Integer sueldo) {
		this.sueldo = sueldo;
	}

	public java.lang.Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(java.lang.Integer sexo) {
		this.sexo = sexo;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public int getMontoBono() {
		return this.montoBono;
	}

	public void setMontoBono(int montoBono) {
		this.montoBono = montoBono;
	}

	public Solicitante(java.lang.Integer run, java.lang.String nombre,
			java.lang.Integer edad, java.lang.Integer numHijos,
			java.lang.Integer estadoCivil, java.lang.Integer sueldo,
			java.lang.Integer sexo) {
		this.run = run;
		this.nombre = nombre;
		this.edad = edad;
		this.numHijos = numHijos;
		this.estadoCivil = estadoCivil;
		this.sueldo = sueldo;
		this.sexo = sexo;
		this.montoBono = 0;
		this.mensaje = "";
	}

	@Override
	public String toString() {
		return "{\"run\":" + this.run + ",\"nombre\":\"" + this.nombre
				+ "\",\"edad\":" + this.edad + ",\"numHijos\":" + this.numHijos
				+ ",\"estadoCivil\":" + this.estadoCivil + ",\"sueldo\":"
				+ this.sueldo + ",\"sexo\":" + this.sexo + ",\"montoBono\":"
				+ this.montoBono + ",\"mensaje\":\"" + this.mensaje + "\"}";
	}

}